#!/bin/bash
#lr install 
#written by xiewei 2004 
#Re-implemented by lty 2018

lr_dir=~/.lr_data
bin_dir=/etc/lr
prof_dir=/etc/profile.d

setup()
{
    if [ -e $lr_dir ]
    then	
 	echo -n "You have installed lr , overwrite it(y\Y or n\N)? "
 	read choice
        if [ $choice = "n" -o $choice = "N" ]
        then
            mkdir $bin_dir
	    cp -f ./package/lr $bin_dir/
	    cp -f ./package/lr.sh $prof_dir/
	    echo "install lr OK, but do not overwrite it!"
	    echo "version is 1.00"
            echo ". /etc/profile.d/lr.sh" >> ~/.bashrc
            source ~/.bashrc
	    exit 0
        fi
    fi

    mkdir $bin_dir
    cp -f ./package/lr $bin_dir/
    cp -f ./package/lr.sh $prof_dir/
    echo ". /etc/profile.d/lr.sh" >> ~/.bashrc
    source ~/.bashrc
}

delete()
{
    echo -n "Are you sure to delete lr(y\Y or n\N)? "
    read choice
    if [ "$choice" = "N" -o "$choice" = "n" ]
    then
	echo "Nothing to do!"
	exit 0
    fi

    rm -rf $bin_dir
    rm -f  $prof_dir/lr.sh
}

usage()
{
    echo "<install> install lr on your computer."
    echo "<install del> delete lr from your computer."
    exit 1
}

echo "Installing Software lr"
echo "Written By XieWei 2004" 
echo "Re-implemented By lty at Dec31th, 2018" 

if [ $# -eq 0 ]
then
    setup
    echo "lr is installed successfully!"
    echo "version is 1.00"
    exit 0
else if [ $# -gt 1 ]
     then
        usage
     else
        case $1 in
            del)
               delete
               echo "have delete lr OK!"
               ;;
            *)
               usage
               ;;
        esac
     fi
fi
